services:
  sonarqube:
    image: sonarqube:latest
    container_name: sonarqube
    restart: unless-stopped
    networks:
      - traefik_net
    environment:
      - SONAR_ES_BOOTSTRAP_CHECKS_DISABLE=true
      - SONAR_FORCEAUTHENTICATION=true
    volumes:
      - sonarqube_data:/opt/sonarqube/data
      - sonarqube_extensions:/opt/sonarqube/extensions
      - sonarqube_logs:/opt/sonarqube/logs
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.sonarqube.rule=Host(`sonarqube.${DOMAIN_NAME}`)"
      - "traefik.http.routers.sonarqube.entrypoints=websecure"
      - "traefik.http.routers.sonarqube.tls.certresolver=cloudflare"
      - "traefik.http.services.sonarqube.loadbalancer.server.port=9000"

volumes:
  sonarqube_data:
  sonarqube_extensions:
  sonarqube_logs:


networks:
  traefik_net:
    external: true
